# mkdocs.yml
# Project information
site_name: mlops kubeflow
site_author: Fahim Rustamy
site_description: >-
  A machine learning platform with Kubeflow
# Repository
repo_name: RustamyF/mlops-kubeflow
repo_url: https://github.com/RustamyF/mlops-kubeflow

theme:
  name: "material"
  features:
    - content.code.annotate

nav:
  - index.md
  - notebook.md
  - pipeline.md



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/frustamy
